# Generated by Django 5.0.6 on 2024-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='courses', related_query_name='course', to='recognition.student'),
        ),
    ]
