# Generated by Django 5.0.6 on 2024-06-14 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_alter_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_detected', models.DateTimeField()),
                ('last_detected', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.student')),
            ],
        ),
    ]
